spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/depgirpro
    username: root
    password: Matius171007
    driver-class-name: org.mariadb.jdbc.Driver

jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect
