spring:
  datasource:
    url: jdbc:mariadb://45.93.101.18:3306/u440037415_dev_depgirpro
    username: u440037415_dev_depgirpro
    password: Ttlgs*2023++$
    driver-class-name: org.mariadb.jdbc.Driver
